import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import Header from '../components/Header'
import Modal from '../components/Modal'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>insta 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/instagram.png" />
      </Head>

    <Modal/>
      {/* header */}
      <Header />
      {/* feed */}
      <Feed/>
      {/* modal */}
    </div>
  )
}
